# Site settings
title: Pablo Hiroshi
description: Pablo Hiroshi's personal webpage
url: https://pablohiro.github.io
github_username: pablohiro
minimal_mistakes_skin: default

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
include:
  - _pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
repository: https://github.com/PabloHiro/page.git
author:
  name: Pablo Hiroshi
  bio: YAML engineer ;)
  links:
    - label: "Github"
      icon: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
      url: https://github.com/PabloHiro
footer:
  links:
    - label: "Github"
      icon: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
      url: https://github.com/PabloHiro