# Site settings
title: Pablo Hiroshi
description: Pablo Hiroshi's personal webpage
url: https://pablohiro.github.io
baseurl: page
github_username: pablohiro
minimal_mistakes_skin: dirt

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
include:
  - _pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
repository: PabloHiro/page
author:
  name: Pablo Hiroshi
  avatar: "/assets/images/profile.jpg"
  bio: YAML engineer ;)
  links:
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: https://github.com/PabloHiro
    - label: Linkedin
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/pablo-hiroshi-alonso/
date_format: "%Y-%m-%d"
atom_feed:
  hide: true
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
