# Site settings
title: Pablo Hiroshi
description: Pablo Hiroshi's personal webpage
url: https://pablohiro.github.io
github_username: pablohiro
source: src
destination: /

# Build settings
markdown: kramdown