# Site settings
title: Pablo Hiroshi
description: Pablo Hiroshi's personal webpage
url: https://pablohiro.github.io
baseurl: page
github_username: pablohiro
minimal_mistakes_skin: dirt

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
include:
  - _pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
repository: PabloHiro/page
author:
  name: Pablo Hiroshi
  bio: YAML engineer ;)
  links:
    - label: "Github"
      icon: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
      url: https://github.com/PabloHiro
    - label: Linkedin
      icon: https://content.linkedin.com/content/dam/me/news/en-us/blog/authors/l/li-logo.png.original.png
      url: https://www.linkedin.com/in/pablo-hiroshi-alonso/
date_format: "%Y-%m-%d"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      share: true
      author_profile: true
